services:
  next:
    build:
      context: ./frontend
    ports:
      - "3004:3000"
    networks:
      - cool
    depends_on:
      - laravel
    environment:
      API_URL: http://laravel

  laravel:
    build:
      context: ./backend
    ports:
      - "8080:80"
    networks:
      - cool
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    ports:
      - "9891:5432"
    networks:
      - cool
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

networks:
  cool:
    driver: bridge
