services:
  ez-next:
    build:
      context: ./frontend
    ports:
      - "3004:3000"
    networks:
      - cool
    depends_on:
      - ez-laravel
    environment:
      API_URL: http://ez-laravel

  ez-laravel:
    build:
      context: ./backend
    ports:
      - "8080:80"
    networks:
      - cool
    depends_on:
      - ez-postgres

  ez-postgres:
    image: postgres:latest
    ports:
      - "9891:5432"
    networks:
      - cool
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

networks:
  cool:
    driver: bridge